// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: proto/agentwarden/v1/events.proto

package wardenapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Action        *Action                `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Context       *ActionContext         `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionEvent) Reset() {
	*x = ActionEvent{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEvent) ProtoMessage() {}

func (x *ActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEvent.ProtoReflect.Descriptor instead.
func (*ActionEvent) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *ActionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ActionEvent) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ActionEvent) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionEvent) GetContext() *ActionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ActionEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                               // e.g. "tool.call", "api.request"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // e.g. "github.merge_pr"
	ParamsJson    string                 `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // JSON-encoded params
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                           // e.g. "github.com/org/repo"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *Action) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ActionContext struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SessionCost            float64                `protobuf:"fixed64,1,opt,name=session_cost,json=sessionCost,proto3" json:"session_cost,omitempty"`
	SessionActionCount     int32                  `protobuf:"varint,2,opt,name=session_action_count,json=sessionActionCount,proto3" json:"session_action_count,omitempty"`
	SessionDurationSeconds int32                  `protobuf:"varint,3,opt,name=session_duration_seconds,json=sessionDurationSeconds,proto3" json:"session_duration_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ActionContext) Reset() {
	*x = ActionContext{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionContext) ProtoMessage() {}

func (x *ActionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionContext.ProtoReflect.Descriptor instead.
func (*ActionContext) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ActionContext) GetSessionCost() float64 {
	if x != nil {
		return x.SessionCost
	}
	return 0
}

func (x *ActionContext) GetSessionActionCount() int32 {
	if x != nil {
		return x.SessionActionCount
	}
	return 0
}

func (x *ActionContext) GetSessionDurationSeconds() int32 {
	if x != nil {
		return x.SessionDurationSeconds
	}
	return 0
}

type Verdict struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verdict        string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"` // allow, deny, terminate, approve, throttle
	TraceId        string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PolicyName     string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ApprovalId     string                 `protobuf:"bytes,5,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	LatencyMs      int32                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Suggestions    []string               `protobuf:"bytes,8,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *Verdict) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *Verdict) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Verdict) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Verdict) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Verdict) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *Verdict) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Verdict) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Verdict) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type SessionStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *SessionStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionStart) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SessionStart) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SessionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAck) Reset() {
	*x = SessionAck{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAck) ProtoMessage() {}

func (x *SessionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAck.ProtoReflect.Descriptor instead.
func (*SessionAck) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *SessionAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SessionAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SessionEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEnd) Reset() {
	*x = SessionEnd{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnd) ProtoMessage() {}

func (x *SessionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnd.ProtoReflect.Descriptor instead.
func (*SessionEnd) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *SessionEnd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCost       float64                `protobuf:"fixed64,2,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ActionCount     int32                  `protobuf:"varint,3,opt,name=action_count,json=actionCount,proto3" json:"action_count,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *SessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSummary) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *SessionSummary) GetActionCount() int32 {
	if x != nil {
		return x.ActionCount
	}
	return 0
}

func (x *SessionSummary) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SessionSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SessionScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskCompleted bool                   `protobuf:"varint,2,opt,name=task_completed,json=taskCompleted,proto3" json:"task_completed,omitempty"`
	Quality       float64                `protobuf:"fixed64,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionScore) Reset() {
	*x = SessionScore{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionScore) ProtoMessage() {}

func (x *SessionScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionScore.ProtoReflect.Descriptor instead.
func (*SessionScore) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *SessionScore) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionScore) GetTaskCompleted() bool {
	if x != nil {
		return x.TaskCompleted
	}
	return false
}

func (x *SessionScore) GetQuality() float64 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *SessionScore) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentwarden_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_agentwarden_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_agentwarden_v1_events_proto protoreflect.FileDescriptor

const file_proto_agentwarden_v1_events_proto_rawDesc = "" +
	"\n" +
	"!proto/agentwarden/v1/events.proto\x12\x0eagentwarden.v1\"\xd9\x02\n" +
	"\vActionEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12.\n" +
	"\x06action\x18\x04 \x01(\v2\x16.agentwarden.v1.ActionR\x06action\x127\n" +
	"\acontext\x18\x05 \x01(\v2\x1d.agentwarden.v1.ActionContextR\acontext\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).agentwarden.v1.ActionEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\tR\n" +
	"paramsJson\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\"\x9e\x01\n" +
	"\rActionContext\x12!\n" +
	"\fsession_cost\x18\x01 \x01(\x01R\vsessionCost\x120\n" +
	"\x14session_action_count\x18\x02 \x01(\x05R\x12sessionActionCount\x128\n" +
	"\x18session_duration_seconds\x18\x03 \x01(\x05R\x16sessionDurationSeconds\"\x84\x02\n" +
	"\aVerdict\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vpolicy_name\x18\x03 \x01(\tR\n" +
	"policyName\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vapproval_id\x18\x05 \x01(\tR\n" +
	"approvalId\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x05R\tlatencyMs\x12 \n" +
	"\vsuggestions\x18\b \x03(\tR\vsuggestions\"\xf2\x01\n" +
	"\fSessionStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.agentwarden.v1.SessionStart.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\n" +
	"SessionAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"+\n" +
	"\n" +
	"SessionEnd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb4\x01\n" +
	"\x0eSessionSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x02 \x01(\x01R\ttotalCost\x12!\n" +
	"\faction_count\x18\x03 \x01(\x05R\vactionCount\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xef\x01\n" +
	"\fSessionScore\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0etask_completed\x18\x02 \x01(\bR\rtaskCompleted\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x01R\aquality\x12C\n" +
	"\ametrics\x18\x04 \x03(\v2).agentwarden.v1.SessionScore.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfe\x02\n" +
	"\x12AgentWardenService\x12F\n" +
	"\x0eEvaluateAction\x12\x1b.agentwarden.v1.ActionEvent\x1a\x17.agentwarden.v1.Verdict\x12H\n" +
	"\fStartSession\x12\x1c.agentwarden.v1.SessionStart\x1a\x1a.agentwarden.v1.SessionAck\x12H\n" +
	"\n" +
	"EndSession\x12\x1a.agentwarden.v1.SessionEnd\x1a\x1e.agentwarden.v1.SessionSummary\x12A\n" +
	"\fScoreSession\x12\x1c.agentwarden.v1.SessionScore\x1a\x13.agentwarden.v1.Ack\x12I\n" +
	"\rStreamActions\x12\x1b.agentwarden.v1.ActionEvent\x1a\x17.agentwarden.v1.Verdict(\x010\x01BCZAgithub.com/agentwarden/agentwarden/proto/agentwarden/v1;wardenapib\x06proto3"

var (
	file_proto_agentwarden_v1_events_proto_rawDescOnce sync.Once
	file_proto_agentwarden_v1_events_proto_rawDescData []byte
)

func file_proto_agentwarden_v1_events_proto_rawDescGZIP() []byte {
	file_proto_agentwarden_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_agentwarden_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentwarden_v1_events_proto_rawDesc), len(file_proto_agentwarden_v1_events_proto_rawDesc)))
	})
	return file_proto_agentwarden_v1_events_proto_rawDescData
}

var file_proto_agentwarden_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_agentwarden_v1_events_proto_goTypes = []any{
	(*ActionEvent)(nil),    // 0: agentwarden.v1.ActionEvent
	(*Action)(nil),         // 1: agentwarden.v1.Action
	(*ActionContext)(nil),  // 2: agentwarden.v1.ActionContext
	(*Verdict)(nil),        // 3: agentwarden.v1.Verdict
	(*SessionStart)(nil),   // 4: agentwarden.v1.SessionStart
	(*SessionAck)(nil),     // 5: agentwarden.v1.SessionAck
	(*SessionEnd)(nil),     // 6: agentwarden.v1.SessionEnd
	(*SessionSummary)(nil), // 7: agentwarden.v1.SessionSummary
	(*SessionScore)(nil),   // 8: agentwarden.v1.SessionScore
	(*Ack)(nil),            // 9: agentwarden.v1.Ack
	nil,                    // 10: agentwarden.v1.ActionEvent.MetadataEntry
	nil,                    // 11: agentwarden.v1.SessionStart.MetadataEntry
	nil,                    // 12: agentwarden.v1.SessionScore.MetricsEntry
}
var file_proto_agentwarden_v1_events_proto_depIdxs = []int32{
	1,  // 0: agentwarden.v1.ActionEvent.action:type_name -> agentwarden.v1.Action
	2,  // 1: agentwarden.v1.ActionEvent.context:type_name -> agentwarden.v1.ActionContext
	10, // 2: agentwarden.v1.ActionEvent.metadata:type_name -> agentwarden.v1.ActionEvent.MetadataEntry
	11, // 3: agentwarden.v1.SessionStart.metadata:type_name -> agentwarden.v1.SessionStart.MetadataEntry
	12, // 4: agentwarden.v1.SessionScore.metrics:type_name -> agentwarden.v1.SessionScore.MetricsEntry
	0,  // 5: agentwarden.v1.AgentWardenService.EvaluateAction:input_type -> agentwarden.v1.ActionEvent
	4,  // 6: agentwarden.v1.AgentWardenService.StartSession:input_type -> agentwarden.v1.SessionStart
	6,  // 7: agentwarden.v1.AgentWardenService.EndSession:input_type -> agentwarden.v1.SessionEnd
	8,  // 8: agentwarden.v1.AgentWardenService.ScoreSession:input_type -> agentwarden.v1.SessionScore
	0,  // 9: agentwarden.v1.AgentWardenService.StreamActions:input_type -> agentwarden.v1.ActionEvent
	3,  // 10: agentwarden.v1.AgentWardenService.EvaluateAction:output_type -> agentwarden.v1.Verdict
	5,  // 11: agentwarden.v1.AgentWardenService.StartSession:output_type -> agentwarden.v1.SessionAck
	7,  // 12: agentwarden.v1.AgentWardenService.EndSession:output_type -> agentwarden.v1.SessionSummary
	9,  // 13: agentwarden.v1.AgentWardenService.ScoreSession:output_type -> agentwarden.v1.Ack
	3,  // 14: agentwarden.v1.AgentWardenService.StreamActions:output_type -> agentwarden.v1.Verdict
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_agentwarden_v1_events_proto_init() }
func file_proto_agentwarden_v1_events_proto_init() {
	if File_proto_agentwarden_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentwarden_v1_events_proto_rawDesc), len(file_proto_agentwarden_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentwarden_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_agentwarden_v1_events_proto_depIdxs,
		MessageInfos:      file_proto_agentwarden_v1_events_proto_msgTypes,
	}.Build()
	File_proto_agentwarden_v1_events_proto = out.File
	file_proto_agentwarden_v1_events_proto_goTypes = nil
	file_proto_agentwarden_v1_events_proto_depIdxs = nil
}
