// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.1
// source: proto/agentwarden/v1/events.proto

package wardenapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWardenService_EvaluateAction_FullMethodName = "/agentwarden.v1.AgentWardenService/EvaluateAction"
	AgentWardenService_StartSession_FullMethodName   = "/agentwarden.v1.AgentWardenService/StartSession"
	AgentWardenService_EndSession_FullMethodName     = "/agentwarden.v1.AgentWardenService/EndSession"
	AgentWardenService_ScoreSession_FullMethodName   = "/agentwarden.v1.AgentWardenService/ScoreSession"
	AgentWardenService_StreamActions_FullMethodName  = "/agentwarden.v1.AgentWardenService/StreamActions"
)

// AgentWardenServiceClient is the client API for AgentWardenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentWardenServiceClient interface {
	EvaluateAction(ctx context.Context, in *ActionEvent, opts ...grpc.CallOption) (*Verdict, error)
	StartSession(ctx context.Context, in *SessionStart, opts ...grpc.CallOption) (*SessionAck, error)
	EndSession(ctx context.Context, in *SessionEnd, opts ...grpc.CallOption) (*SessionSummary, error)
	ScoreSession(ctx context.Context, in *SessionScore, opts ...grpc.CallOption) (*Ack, error)
	StreamActions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionEvent, Verdict], error)
}

type agentWardenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWardenServiceClient(cc grpc.ClientConnInterface) AgentWardenServiceClient {
	return &agentWardenServiceClient{cc}
}

func (c *agentWardenServiceClient) EvaluateAction(ctx context.Context, in *ActionEvent, opts ...grpc.CallOption) (*Verdict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Verdict)
	err := c.cc.Invoke(ctx, AgentWardenService_EvaluateAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWardenServiceClient) StartSession(ctx context.Context, in *SessionStart, opts ...grpc.CallOption) (*SessionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionAck)
	err := c.cc.Invoke(ctx, AgentWardenService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWardenServiceClient) EndSession(ctx context.Context, in *SessionEnd, opts ...grpc.CallOption) (*SessionSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionSummary)
	err := c.cc.Invoke(ctx, AgentWardenService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWardenServiceClient) ScoreSession(ctx context.Context, in *SessionScore, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentWardenService_ScoreSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWardenServiceClient) StreamActions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionEvent, Verdict], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentWardenService_ServiceDesc.Streams[0], AgentWardenService_StreamActions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionEvent, Verdict]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWardenService_StreamActionsClient = grpc.BidiStreamingClient[ActionEvent, Verdict]

// AgentWardenServiceServer is the server API for AgentWardenService service.
// All implementations must embed UnimplementedAgentWardenServiceServer
// for forward compatibility.
type AgentWardenServiceServer interface {
	EvaluateAction(context.Context, *ActionEvent) (*Verdict, error)
	StartSession(context.Context, *SessionStart) (*SessionAck, error)
	EndSession(context.Context, *SessionEnd) (*SessionSummary, error)
	ScoreSession(context.Context, *SessionScore) (*Ack, error)
	StreamActions(grpc.BidiStreamingServer[ActionEvent, Verdict]) error
	mustEmbedUnimplementedAgentWardenServiceServer()
}

// UnimplementedAgentWardenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWardenServiceServer struct{}

func (UnimplementedAgentWardenServiceServer) EvaluateAction(context.Context, *ActionEvent) (*Verdict, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateAction not implemented")
}
func (UnimplementedAgentWardenServiceServer) StartSession(context.Context, *SessionStart) (*SessionAck, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedAgentWardenServiceServer) EndSession(context.Context, *SessionEnd) (*SessionSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedAgentWardenServiceServer) ScoreSession(context.Context, *SessionScore) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreSession not implemented")
}
func (UnimplementedAgentWardenServiceServer) StreamActions(grpc.BidiStreamingServer[ActionEvent, Verdict]) error {
	return status.Error(codes.Unimplemented, "method StreamActions not implemented")
}
func (UnimplementedAgentWardenServiceServer) mustEmbedUnimplementedAgentWardenServiceServer() {}
func (UnimplementedAgentWardenServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentWardenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWardenServiceServer will
// result in compilation errors.
type UnsafeAgentWardenServiceServer interface {
	mustEmbedUnimplementedAgentWardenServiceServer()
}

func RegisterAgentWardenServiceServer(s grpc.ServiceRegistrar, srv AgentWardenServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentWardenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWardenService_ServiceDesc, srv)
}

func _AgentWardenService_EvaluateAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWardenServiceServer).EvaluateAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWardenService_EvaluateAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWardenServiceServer).EvaluateAction(ctx, req.(*ActionEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWardenService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWardenServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWardenService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWardenServiceServer).StartSession(ctx, req.(*SessionStart))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWardenService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionEnd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWardenServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWardenService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWardenServiceServer).EndSession(ctx, req.(*SessionEnd))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWardenService_ScoreSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionScore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWardenServiceServer).ScoreSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWardenService_ScoreSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWardenServiceServer).ScoreSession(ctx, req.(*SessionScore))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWardenService_StreamActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentWardenServiceServer).StreamActions(&grpc.GenericServerStream[ActionEvent, Verdict]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWardenService_StreamActionsServer = grpc.BidiStreamingServer[ActionEvent, Verdict]

// AgentWardenService_ServiceDesc is the grpc.ServiceDesc for AgentWardenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWardenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentwarden.v1.AgentWardenService",
	HandlerType: (*AgentWardenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateAction",
			Handler:    _AgentWardenService_EvaluateAction_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _AgentWardenService_StartSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _AgentWardenService_EndSession_Handler,
		},
		{
			MethodName: "ScoreSession",
			Handler:    _AgentWardenService_ScoreSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamActions",
			Handler:       _AgentWardenService_StreamActions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agentwarden/v1/events.proto",
}
