package config

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"sync"

	"gopkg.in/yaml.v3"
)

var (
	envVarPattern = regexp.MustCompile(`\$\{([^}]+)\}`)
)

// Loader manages configuration loading and hot-reload.
type Loader struct {
	mu       sync.RWMutex
	config   *Config
	filePath string
}

// NewLoader creates a new config loader.
func NewLoader() *Loader {
	return &Loader{
		config: DefaultConfig(),
	}
}

// Load reads and parses a YAML config file.
func (l *Loader) Load(filePath string) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	l.filePath = filePath

	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	// Substitute environment variables
	expanded := substituteEnvVars(string(data))

	cfg := DefaultConfig()
	if err := yaml.Unmarshal([]byte(expanded), cfg); err != nil {
		return fmt.Errorf("failed to parse config file: %w", err)
	}

	l.config = cfg
	return nil
}

// Get returns the current configuration (thread-safe).
func (l *Loader) Get() *Config {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.config
}

// Reload re-reads the config file from disk.
func (l *Loader) Reload() error {
	if l.filePath == "" {
		return fmt.Errorf("no config file loaded")
	}
	return l.Load(l.filePath)
}

// FilePath returns the loaded config file path.
func (l *Loader) FilePath() string {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.filePath
}

// substituteEnvVars replaces ${ENV_VAR} patterns with environment variable values.
func substituteEnvVars(input string) string {
	return envVarPattern.ReplaceAllStringFunc(input, func(match string) string {
		varName := strings.TrimPrefix(strings.TrimSuffix(match, "}"), "${")

		// Support ${VAR:-default} syntax
		parts := strings.SplitN(varName, ":-", 2)
		varName = parts[0]

		value := os.Getenv(varName)
		if value == "" && len(parts) == 2 {
			return parts[1]
		}
		return value
	})
}

// GenerateDefault writes a starter config file to the given path.
func GenerateDefault(filePath string) error {
	starter := `# agentwarden.yaml — AgentWarden Configuration
# Generated by: agentwarden init

server:
  port: 6777
  dashboard: true
  log_level: info
  cors: false

# Upstream LLM provider routing
upstream:
  default: https://api.openai.com/v1
  providers:
    openai: https://api.openai.com/v1
    anthropic: https://api.anthropic.com/v1
    gemini: https://generativelanguage.googleapis.com/v1beta
  passthrough_auth: true
  timeout: 30s
  retries: 2

# Trace storage
storage:
  driver: sqlite
  path: ./agentwarden.db
  retention: 720h  # 30 days

# Governance policies
policies:
  # Cost circuit breaker — kill sessions that exceed budget
  - name: session-budget
    condition: "session.cost > 10.00"
    effect: terminate
    message: "Session killed: exceeded $10 budget"

  # Block dangerous database operations
  - name: no-prod-db-writes
    condition: >
      action.type == "db.query"
      && action.params.query.matches("^(INSERT|UPDATE|DELETE|DROP)")
      && action.target.contains("production")
    effect: deny
    message: "Production database writes are blocked"

  # Rate limiting
  - name: api-rate-limit
    condition: 'session.action_count("api.call", "60s") > 100'
    effect: deny
    message: "Rate limit exceeded: >100 API calls per minute"

# Anomaly detection
detection:
  loop:
    enabled: true
    threshold: 5
    window: 60s
    action: pause
  cost_anomaly:
    enabled: true
    multiplier: 10
    action: alert
  spiral:
    enabled: true
    similarity_threshold: 0.9
    window: 5
    action: alert

# Alerts (optional)
# alerts:
#   slack:
#     webhook_url: ${SLACK_WEBHOOK_URL}
#     channel: "#agent-alerts"
#   webhook:
#     url: https://your-app.com/webhooks/agentwarden
#     secret: ${WEBHOOK_SECRET}

# Self-evolution (disabled by default)
evolution:
  enabled: false
`
	return os.WriteFile(filePath, []byte(starter), 0644)
}
